DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    users_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (users_id ),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    requests_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    requestor_id BIGINT REFERENCES users (users_id ) ON DELETE CASCADE,
    CONSTRAINT pk_request PRIMARY KEY (requests_id)
);

CREATE TABLE IF NOT EXISTS items
(
    items_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    is_available   BOOLEAN                                 NOT NULL DEFAULT FALSE,
    owner_id    BIGINT REFERENCES users (users_id ),
    request_id  BIGINT REFERENCES requests (requests_id),
    CONSTRAINT pk_item PRIMARY KEY (items_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    bookings_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP                               NOT NULL,
    end_date   TIMESTAMP                               NOT NULL,
    item_id    BIGINT REFERENCES items (items_id),
    booker_id  BIGINT REFERENCES users (users_id ),
    status     VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (bookings_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comments_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(255)                            NOT NULL,
    item_id   BIGINT REFERENCES items (items_id),
    author_id BIGINT REFERENCES users (users_id ),
    created_date   TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (comments_id)
);